config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    get :products,                  to: 'products#show'
    resources :categories, only: :show
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# == Route Map
#
#                            Prefix Verb URI Pattern                                  Controller#Action
#                             spree      /                                            Spree::Core::Engine
#                           potepan GET  /potepan(.:format)                           potepan/sample#index
#                     potepan_index GET  /potepan/index(.:format)                     potepan/sample#index
# potepan_product_grid_left_sidebar GET  /potepan/product_grid_left_sidebar(.:format) potepan/sample#product_grid_left_sidebar
# potepan_product_list_left_sidebar GET  /potepan/product_list_left_sidebar(.:format) potepan/sample#product_list_left_sidebar
#            potepan_single_product GET  /potepan/single_product(.:format)            potepan/sample#single_product
#                 potepan_cart_page GET  /potepan/cart_page(.:format)                 potepan/sample#cart_page
#           potepan_checkout_step_1 GET  /potepan/checkout_step_1(.:format)           potepan/sample#checkout_step_1
#           potepan_checkout_step_2 GET  /potepan/checkout_step_2(.:format)           potepan/sample#checkout_step_2
#           potepan_checkout_step_3 GET  /potepan/checkout_step_3(.:format)           potepan/sample#checkout_step_3
#         potepan_checkout_complete GET  /potepan/checkout_complete(.:format)         potepan/sample#checkout_complete
#         potepan_blog_left_sidebar GET  /potepan/blog_left_sidebar(.:format)         potepan/sample#blog_left_sidebar
#        potepan_blog_right_sidebar GET  /potepan/blog_right_sidebar(.:format)        potepan/sample#blog_right_sidebar
#  potepan_blog_single_left_sidebar GET  /potepan/blog_single_left_sidebar(.:format)  potepan/sample#blog_single_left_sidebar
# potepan_blog_single_right_sidebar GET  /potepan/blog_single_right_sidebar(.:format) potepan/sample#blog_single_right_sidebar
#                  potepan_about_us GET  /potepan/about_us(.:format)                  potepan/sample#about_us
#                 potepan_tokushoho GET  /potepan/tokushoho(.:format)                 potepan/sample#tokushoho
#            potepan_privacy_policy GET  /potepan/privacy_policy(.:format)            potepan/sample#privacy_policy
#                  potepan_products GET  /potepan/products(.:format)                  potepan/products#show
#                  potepan_category GET  /potepan/categories/:id(.:format)            potepan/categories#show
#
# Routes for Spree::Core::Engine:
#                                                  set_locale POST   /locale/set(.:format)                                                                              spree/locale#set {:format=>:json}
#                                                admin_locale GET    /admin/locale(.:format)                                                                            spree/admin/locales#show
#                                                             PATCH  /admin/locale(.:format)                                                                            spree/admin/locales#update
#                                                             PUT    /admin/locale(.:format)                                                                            spree/admin/locales#update
#                                      new_spree_user_session GET    /user/spree_user/sign_in(.:format)                                                                 spree/user_sessions#new
#                                          spree_user_session POST   /user/spree_user/sign_in(.:format)                                                                 spree/user_sessions#create
#                                  destroy_spree_user_session GET    /user/spree_user/logout(.:format)                                                                  spree/user_sessions#destroy
#                                     new_spree_user_password GET    /user/spree_user/password/new(.:format)                                                            spree/user_passwords#new
#                                    edit_spree_user_password GET    /user/spree_user/password/edit(.:format)                                                           spree/user_passwords#edit
#                                         spree_user_password PATCH  /user/spree_user/password(.:format)                                                                spree/user_passwords#update
#                                                             PUT    /user/spree_user/password(.:format)                                                                spree/user_passwords#update
#                                                             POST   /user/spree_user/password(.:format)                                                                spree/user_passwords#create
#                              cancel_spree_user_registration GET    /user/spree_user/cancel(.:format)                                                                  spree/user_registrations#cancel
#                                 new_spree_user_registration GET    /user/spree_user/sign_up(.:format)                                                                 spree/user_registrations#new
#                                edit_spree_user_registration GET    /user/spree_user/edit(.:format)                                                                    spree/user_registrations#edit
#                                     spree_user_registration PATCH  /user/spree_user(.:format)                                                                         spree/user_registrations#update
#                                                             PUT    /user/spree_user(.:format)                                                                         spree/user_registrations#update
#                                                             DELETE /user/spree_user(.:format)                                                                         spree/user_registrations#destroy
#                                                             POST   /user/spree_user(.:format)                                                                         spree/user_registrations#create
#                                                   edit_user GET    /users/:id/edit(.:format)                                                                          spree/users#edit
#                                                        user PATCH  /users/:id(.:format)                                                                               spree/users#update
#                                                             PUT    /users/:id(.:format)                                                                               spree/users#update
#                                                       login GET    /login(.:format)                                                                                   spree/user_sessions#new
#                                          create_new_session POST   /login(.:format)                                                                                   spree/user_sessions#create
#                                                      logout GET    /logout(.:format)                                                                                  spree/user_sessions#destroy
#                                                      signup GET    /signup(.:format)                                                                                  spree/user_registrations#new
#                                                registration POST   /signup(.:format)                                                                                  spree/user_registrations#create
#                                            recover_password GET    /password/recover(.:format)                                                                        spree/user_passwords#new
#                                              reset_password POST   /password/recover(.:format)                                                                        spree/user_passwords#create

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @category = Spree::Taxon.find(params[:id])
    @products = @category.products
    # サイドバー
    @category_taxons = Spree::Taxon.find_by(name: 'Categories').leaves
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.first
    @related_products = Spree::Taxon.find(@product.taxons.second).products.where.not(id: @product.id).limit(4)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment(:small)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <a href="single_product.html">
        <h5><%= product.name %></h5>
      </a>
      <h3>$<%= product.price %></h3>
    </div>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<%= provide :title ,"Product Grid Sidebar Left - BIGBAG Store" %>
<!-- LIGHT SECTION -->

<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @category.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= @category.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul class="nav navbar-nav side-nav">
                <li>
                  <a href="javascript:;" data-toggle="collapse" data-target="#women">Categories<i class="fa fa-plus"></i></a>
                  <ul id="women" class="collapse collapseItem">
                    <% @category_taxons.each do |taxon| %>
                      <li><a href="<%= potepan_category_path(taxon.id) %>"><i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %>&nbsp;<span>(<%= taxon.products.count %>)</span></a></li>
                    <% end %>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default priceRange">
          <div class="panel-heading">値段から探す</div>
          <div class="panel-body clearfix">
            <div class="price-slider-inner">
                    <span class="amount-wrapper">
                      <input type="text" id="price-amount-1" readonly>
                      <strong>-</strong>
                      <input type="text" id="price-amount-2" readonly>
                    </span>
              <div id="price-range"></div>
            </div>
            <input class="btn btn-default" type="submit" value="絞り込む">
            <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <li><a href="#">ブラック<span>(15)</span></a></li>
              <li><a href="#">ホワイト<span>(10)</span></a></li>
              <li><a href="#">レッド<span>(7)</span></a></li>
              <li><a href="#">ブルー<span>(12)</span></a></li>
              <li><a href="#">オレンジ<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <li><a href="#">S<span>(15)</span></a></li>
              <li><a href="#">M<span>(10)</span></a></li>
              <li><a href="#">L<span>(7)</span></a></li>
              <li><a href="#">XL<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: "product", collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
